todoproject/todoapp/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'todoapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:todo_id>/', views.detail, name='detail'),
]

todoproject/todoproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todoapp/', include('todoapp.urls')),
]

todoproject/todoapp/models.py
from django.db import models

# Create your models here.

class Todo(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name

todoproject/todoapp/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse

from .models import Todo

# Create your views here.

def index(request):
    todo_list = Todo.objects.all()
    context = {'todo_list': todo_list}
    return render(request, 'todoapp/index.html', context)

def detail(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    return render(request, 'todoapp/detail.html', {'todo': todo})

todoproject/todoapp/templates/todoapp/detail.html
<h1>{{ todo.name }}</h1>

<a href="{% url 'todoapp:index' %}">Zurück</a>

{% if errer_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

todoproject/todoapp/templates/todoapp/index.html
{% if todo_list %}
<h3>Aktuelle Todo's</h3>

<table border=1>
  <tr>
    <th width=200>Todo</th>
    <th width=150>Status</th>
    <th width=150>Status ändern</th>
  </tr>
  {% for todo in todo_list %}
  <tr>
    <td><a href="{% url 'todoapp:detail' todo.id %}">{{ todo.name }}</a></td>
    <td>/</td>
    <td>/</td>
   </tr>
   {% endfor %}
</table>

{% else %}
    <p>Keine Todo's.</p>
{% endif %}